### PR TITLE
chore: update to last tfsec v1.28.1

### PR DESCRIPTION
**Pull request by lemeurherve**

### CODE REVIEW

**Comment by lemeurherve** [comment]
Ping @owenrumney could this PR be merged?
It would allow us to keep using chocolatey to update this tool in [our image](https://github.com/jenkins-infra/packer-images) instead of retrieving and installing it manually.

**Comment by lemeurherve** [comment]
Gentle ping @liamg 🙂

**Comment by sholt-hpt** [comment]
Gentle bump @liamg @owenrumney

**Comment by liamg** [comment]
@samholtheywood @lemeurherve Sorry guys, we're no longer maintainers of this project - I would suggest calling attention to this on the Aqua Security Slack: https://slack.aquasec.com/

**Comment by giorod3** [comment]
Hi @lemeurherve, thank you for the contribution! I will be taking over this repo, please give me some time to review the code .

**Review by giorod3 — APPROVED** [review]

**Pull request merged**
